services:
  # Backend API Service
  - type: web
    name: mbspro-api
    env: node
    plan: starter
    buildCommand: |
      chmod +x build-render.sh && ./build-render.sh
    startCommand: |
      pnpm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: PINECONE_API_KEY
        sync: false
      - key: COHERE_API_KEY
        sync: false

  # Frontend Web Service
  - type: web
    name: mbspro-web
    env: node
    plan: starter
    buildCommand: |
      chmod +x build.sh && ./build.sh
    startCommand: |
      pnpm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10001
      - key: NEXT_PUBLIC_API_URL
        value: https://mbspro-api.onrender.com
      - key: NEXT_PUBLIC_SUPABASE_URL
        sync: false
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        sync: false

  # PostgreSQL Database
  - type: pserv
    name: mbspro-db
    env: postgres
    plan: starter
    ipAllowList: []
