services:
  # Backend API Service
  - type: web
    name: mbspro-api
    env: node
    plan: starter
    buildCommand: npm install -g pnpm && pnpm install --frozen-lockfile && pnpm --filter @mbspro/api build && ls -la apps/api/dist/suggest/
    startCommand: cd apps/api/dist && node apps/api/src/main.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
      - key: API_PREFIX
        value: api
      - key: SWAGGER_ENABLED
        value: true
      - key: FRONTEND_URL
        value: https://mbspro-web.onrender.com
      - key: MBS_RULES_JSON
        value: suggest/mbs_rules.normalized.json
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: PGSSLMODE
        value: require

  # Frontend Web Service
  - type: web
    name: mbspro-web
    env: node
    plan: starter
    buildCommand: npm install -g pnpm && pnpm install --frozen-lockfile && pnpm --filter @mbspro/web build
    startCommand: cd apps/web && pnpm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_API_BASE
        value: https://mbspro-api.onrender.com
